include $(THEOS)/makefiles/common.mk

TOOL_NAME = launchctl_wrapper

launchctl_wrapper_FILES = main.m
launchctl_wrapper_CFLAGS = -fobjc-arc
launchctl_wrapper_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
